### ISSUE TITLE
Login for projects already on site

### ISSUE THREAD

**Issue by amandaCCF** [codeforkansascity/CommunityKC#37]
By mid-May would be great to notify all existing project contacts with instructions to login/create account and update their profile/project.

**Comment by ctraltdel** [comment]
Currently all project nodes have Dave's user assigned as the author. In order to allow the projects to be edited by their owners we will need to create new Drupal accounts based on the project contact name and email, assign them as authors to their projects, and send the users a one-time login link to set a password and access the site. There are at least 143 projects that need to be updated so it would be preferable to automate the process.

**Comment by ctraltdel** [comment]
Did some prep work to get ready to populate this data hopefully next week.

**Comment by ctraltdel** [comment]
All projects are populated with users tied to the name and email of the lead contact now. We will still need to send out a notification for everyone with new accounts to log in and select a password.
