### ISSUE TITLE
Update online form to add a project

### ISSUE THREAD

**Issue by amandaCCF** [codeforkansascity/CommunityKC#39]
Attached are some updates i'd like to have made to the Add a Project online form. Edits are highlighted. Thanks!
[Edits to Project form_3-21-16.docx](https://github.com/codeforkansascity/CommunityKC/files/214146/Edits.to.Project.form_3-21-16.docx)

**Comment by lacrone** [comment]
I think this has been done, I need to double check

**Comment by silasck** [comment]
It has not.

**Comment by lacrone** [comment]
Made most of the updates. Some notes:

-still exploring ways to add descriptions to the taxonomy terms
-can't remove "co-op" organization type since it was already in use
-I'm not able to alter the address input to limit states to MO and KS without digging deeper. Issue #14 is similar so maybe we can adjust fix this at the same time

**Comment by lacrone** [comment]
Added a tooltip message to project type' to explain capacity building. Message disappears when anything is clicked.
