### ISSUE TITLE
Search Behavior

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/CommunityKC#51]
Is there a way we can make the type-search find partial words? 

For example: If I want to find 'St. Joseph's Neighborhood Garden' and I type into the search 'Joe' right now BikeWalkKC will be the only project that comes up, because there's a person named Joe working on it. If I type in 'St' or 'st.' nothing will come up (it'll actually tell me that I need to enter more characters for it to be a valid search.) If I type in 'Jose' nothing will come up. But, if I search 'Joseph' then it will come up. 

I think it's that the search doesn't recognize partial words. It's the same with trying to find any garden project by typing the word 'gar', no results. 

Sorry, this is a little tl;dr-ish

**Comment by lacrone** [comment]
Right now search is able to find variations on the same root word, but not portions of words that don't make sense on their own. Personally I think it's best to keep it this way, since partial word matching would result in a very high number of erroneous results, and would probably mess with relevancy ranking as well.
